[package]
name = "aoc_2020_day_4_part_2"
version = "0.1.0"
authors = ["Gabriel Lacroix <lacroixgabriel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4"